// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using NewModule;

// ReSharper disable once CheckNamespace
namespace NewModule.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IModuleAppService), typeof(ModuleClientProxy))]
public partial class ModuleClientProxy : ClientProxyBase<IModuleAppService>, IModuleAppService
{
    public virtual async Task<bool> SetModAttAsync(string m)
    {
        return await RequestAsync<bool>(nameof(SetModAttAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), m }
        });
    }
}
