// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using TestProject;

// ReSharper disable once CheckNamespace
namespace TestProject.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMainAppService), typeof(MainClientProxy))]
public partial class MainClientProxy : ClientProxyBase<IMainAppService>, IMainAppService
{
    public virtual async Task<bool> SetMainAttAsync(string m)
    {
        return await RequestAsync<bool>(nameof(SetMainAttAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), m }
        });
    }
}
